/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ToDo {
      
    export type TaskStruct = {id: BigNumberish, content: string, completed: boolean}

    export type TaskStructOutput = [id: bigint, content: string, completed: boolean] & {id: bigint, content: string, completed: boolean }
  
    }

  export interface ToDoInterface extends Interface {
    getFunction(nameOrSignature: "createTask" | "deleteTask" | "getCompletedTasks" | "getPendingTasks" | "getTask" | "getTaskById" | "getTotalTasks" | "toggleTask" | "updateTask"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'createTask', values: [string]): string;
encodeFunctionData(functionFragment: 'deleteTask', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCompletedTasks', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPendingTasks', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTask', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTaskById', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTotalTasks', values?: undefined): string;
encodeFunctionData(functionFragment: 'toggleTask', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateTask', values: [BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'createTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deleteTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCompletedTasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingTasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTaskById', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalTasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'toggleTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTask', data: BytesLike): Result;
  }

  

  export interface ToDo extends BaseContract {
    
    connect(runner?: ContractRunner | null): ToDo;
    waitForDeployment(): Promise<this>;

    interface: ToDoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createTask: TypedContractMethod<
      [_content: string, ],
      [void],
      'nonpayable'
    >
    

    
    deleteTask: TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getCompletedTasks: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPendingTasks: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTask: TypedContractMethod<
      [],
      [ToDo.TaskStructOutput[]],
      'view'
    >
    

    
    getTaskById: TypedContractMethod<
      [taskId: BigNumberish, ],
      [ToDo.TaskStructOutput],
      'view'
    >
    

    
    getTotalTasks: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    toggleTask: TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateTask: TypedContractMethod<
      [taskId: BigNumberish, newContent: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createTask'): TypedContractMethod<
      [_content: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deleteTask'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCompletedTasks'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingTasks'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTask'): TypedContractMethod<
      [],
      [ToDo.TaskStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTaskById'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [ToDo.TaskStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalTasks'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'toggleTask'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTask'): TypedContractMethod<
      [taskId: BigNumberish, newContent: string, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }